### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by justin0022** [UBC-LFS/lfs-mass-mailer#10]
Tried to run it off a Windows machine - lots of little errors to fix.

**Comment by patricklinpl** [comment]
Windows Errors 

1. package.json scripts need to be cross platform. fix f10d19b
2. Error with multer saving files on windows. fix f10d19b
3. CSV uses different file type on windows. See commit 8a7b948 for fix 
4. Parsed CSV on windows returns an empty object. See commit 19f5766 for fix
